/**
	Attention: do not modify autogenerated content

	Autogenerated by pixelfont from https://github.com/romsila/pixeltools
	Copyright (c) 2023, Roman Koch, koch.roman@gmail.com
	All rights reserved

	SPDX-License-Identifier: MIT
*/

#ifndef __FONT_NORMAL_H__
#define __FONT_NORMAL_H__

extern const unsigned char NORMAL_S_20[16];
extern const unsigned char NORMAL_S_21[16];
extern const unsigned char NORMAL_S_22[16];
extern const unsigned char NORMAL_S_23[16];
extern const unsigned char NORMAL_S_24[16];
extern const unsigned char NORMAL_S_25[16];
extern const unsigned char NORMAL_S_26[16];
extern const unsigned char NORMAL_S_27[16];
extern const unsigned char NORMAL_S_28[16];
extern const unsigned char NORMAL_S_29[16];
extern const unsigned char NORMAL_S_2A[16];
extern const unsigned char NORMAL_S_2B[16];
extern const unsigned char NORMAL_S_2C[16];
extern const unsigned char NORMAL_S_2D[16];
extern const unsigned char NORMAL_S_2E[16];
extern const unsigned char NORMAL_S_2F[16];
extern const unsigned char NORMAL_S_30[16];
extern const unsigned char NORMAL_S_31[16];
extern const unsigned char NORMAL_S_32[16];
extern const unsigned char NORMAL_S_33[16];
extern const unsigned char NORMAL_S_34[16];
extern const unsigned char NORMAL_S_35[16];
extern const unsigned char NORMAL_S_36[16];
extern const unsigned char NORMAL_S_37[16];
extern const unsigned char NORMAL_S_38[16];
extern const unsigned char NORMAL_S_39[16];
extern const unsigned char NORMAL_S_3A[16];
extern const unsigned char NORMAL_S_3B[16];
extern const unsigned char NORMAL_S_3C[16];
extern const unsigned char NORMAL_S_3D[16];
extern const unsigned char NORMAL_S_3E[16];
extern const unsigned char NORMAL_S_3F[16];
extern const unsigned char NORMAL_S_40[16];
extern const unsigned char NORMAL_S_41[16];
extern const unsigned char NORMAL_S_42[16];
extern const unsigned char NORMAL_S_43[16];
extern const unsigned char NORMAL_S_44[16];
extern const unsigned char NORMAL_S_45[16];
extern const unsigned char NORMAL_S_46[16];
extern const unsigned char NORMAL_S_47[16];
extern const unsigned char NORMAL_S_48[16];
extern const unsigned char NORMAL_S_49[16];
extern const unsigned char NORMAL_S_4A[16];
extern const unsigned char NORMAL_S_4B[16];
extern const unsigned char NORMAL_S_4C[16];
extern const unsigned char NORMAL_S_4D[16];
extern const unsigned char NORMAL_S_4E[16];
extern const unsigned char NORMAL_S_4F[16];
extern const unsigned char NORMAL_S_50[16];
extern const unsigned char NORMAL_S_51[16];
extern const unsigned char NORMAL_S_52[16];
extern const unsigned char NORMAL_S_53[16];
extern const unsigned char NORMAL_S_54[16];
extern const unsigned char NORMAL_S_55[16];
extern const unsigned char NORMAL_S_56[16];
extern const unsigned char NORMAL_S_57[16];
extern const unsigned char NORMAL_S_58[16];
extern const unsigned char NORMAL_S_59[16];
extern const unsigned char NORMAL_S_5A[16];
extern const unsigned char NORMAL_S_5B[16];
extern const unsigned char NORMAL_S_5C[16];
extern const unsigned char NORMAL_S_5D[16];
extern const unsigned char NORMAL_S_5E[16];
extern const unsigned char NORMAL_S_5F[16];
extern const unsigned char NORMAL_S_60[16];
extern const unsigned char NORMAL_S_61[16];
extern const unsigned char NORMAL_S_62[16];
extern const unsigned char NORMAL_S_63[16];
extern const unsigned char NORMAL_S_64[16];
extern const unsigned char NORMAL_S_65[16];
extern const unsigned char NORMAL_S_66[16];
extern const unsigned char NORMAL_S_67[16];
extern const unsigned char NORMAL_S_68[16];
extern const unsigned char NORMAL_S_69[16];
extern const unsigned char NORMAL_S_6A[16];
extern const unsigned char NORMAL_S_6B[16];
extern const unsigned char NORMAL_S_6C[16];
extern const unsigned char NORMAL_S_6D[16];
extern const unsigned char NORMAL_S_6E[16];
extern const unsigned char NORMAL_S_6F[16];
extern const unsigned char NORMAL_S_70[16];
extern const unsigned char NORMAL_S_71[16];
extern const unsigned char NORMAL_S_72[16];
extern const unsigned char NORMAL_S_73[16];
extern const unsigned char NORMAL_S_74[16];
extern const unsigned char NORMAL_S_75[16];
extern const unsigned char NORMAL_S_76[16];
extern const unsigned char NORMAL_S_77[16];
extern const unsigned char NORMAL_S_78[16];
extern const unsigned char NORMAL_S_79[16];
extern const unsigned char NORMAL_S_7A[16];
extern const unsigned char NORMAL_S_7B[16];
extern const unsigned char NORMAL_S_7C[16];
extern const unsigned char NORMAL_S_7D[16];
extern const unsigned char NORMAL_S_7E[16];
extern const unsigned char NORMAL_S_00[16];
extern const unsigned char *FONT_TABLE_NORMAL[128];

#endif // __FONT_NORMAL_H__

