/**
	Attention: do not modify autogenerated content

	Autogenerated by pixelfont from https://github.com/romsila/pixeltools
	Copyright (c) 2023, Roman Koch, koch.roman@gmail.com
	All rights reserved

	SPDX-License-Identifier: MIT
*/

#ifndef __FONT_BIG_H__
#define __FONT_BIG_H__

extern const unsigned char BIG_S_20[48];
extern const unsigned char BIG_S_21[48];
extern const unsigned char BIG_S_22[48];
extern const unsigned char BIG_S_23[48];
extern const unsigned char BIG_S_24[48];
extern const unsigned char BIG_S_25[48];
extern const unsigned char BIG_S_26[48];
extern const unsigned char BIG_S_27[48];
extern const unsigned char BIG_S_28[48];
extern const unsigned char BIG_S_29[48];
extern const unsigned char BIG_S_2A[48];
extern const unsigned char BIG_S_2B[48];
extern const unsigned char BIG_S_2C[48];
extern const unsigned char BIG_S_2D[48];
extern const unsigned char BIG_S_2E[48];
extern const unsigned char BIG_S_2F[48];
extern const unsigned char BIG_S_30[48];
extern const unsigned char BIG_S_31[48];
extern const unsigned char BIG_S_32[48];
extern const unsigned char BIG_S_33[48];
extern const unsigned char BIG_S_34[48];
extern const unsigned char BIG_S_35[48];
extern const unsigned char BIG_S_36[48];
extern const unsigned char BIG_S_37[48];
extern const unsigned char BIG_S_38[48];
extern const unsigned char BIG_S_39[48];
extern const unsigned char BIG_S_3A[48];
extern const unsigned char BIG_S_3B[48];
extern const unsigned char BIG_S_3C[48];
extern const unsigned char BIG_S_3D[48];
extern const unsigned char BIG_S_3E[48];
extern const unsigned char BIG_S_3F[48];
extern const unsigned char BIG_S_40[48];
extern const unsigned char BIG_S_41[48];
extern const unsigned char BIG_S_42[48];
extern const unsigned char BIG_S_43[48];
extern const unsigned char BIG_S_44[48];
extern const unsigned char BIG_S_45[48];
extern const unsigned char BIG_S_46[48];
extern const unsigned char BIG_S_47[48];
extern const unsigned char BIG_S_48[48];
extern const unsigned char BIG_S_49[48];
extern const unsigned char BIG_S_4A[48];
extern const unsigned char BIG_S_4B[48];
extern const unsigned char BIG_S_4C[48];
extern const unsigned char BIG_S_4D[48];
extern const unsigned char BIG_S_4E[48];
extern const unsigned char BIG_S_4F[48];
extern const unsigned char BIG_S_50[48];
extern const unsigned char BIG_S_51[48];
extern const unsigned char BIG_S_52[48];
extern const unsigned char BIG_S_53[48];
extern const unsigned char BIG_S_54[48];
extern const unsigned char BIG_S_55[48];
extern const unsigned char BIG_S_56[48];
extern const unsigned char BIG_S_57[48];
extern const unsigned char BIG_S_58[48];
extern const unsigned char BIG_S_59[48];
extern const unsigned char BIG_S_5A[48];
extern const unsigned char BIG_S_5B[48];
extern const unsigned char BIG_S_5C[48];
extern const unsigned char BIG_S_5D[48];
extern const unsigned char BIG_S_5E[48];
extern const unsigned char BIG_S_5F[48];
extern const unsigned char BIG_S_60[48];
extern const unsigned char BIG_S_61[48];
extern const unsigned char BIG_S_62[48];
extern const unsigned char BIG_S_63[48];
extern const unsigned char BIG_S_64[48];
extern const unsigned char BIG_S_65[48];
extern const unsigned char BIG_S_66[48];
extern const unsigned char BIG_S_67[48];
extern const unsigned char BIG_S_68[48];
extern const unsigned char BIG_S_69[48];
extern const unsigned char BIG_S_6A[48];
extern const unsigned char BIG_S_6B[48];
extern const unsigned char BIG_S_6C[48];
extern const unsigned char BIG_S_6D[48];
extern const unsigned char BIG_S_6E[48];
extern const unsigned char BIG_S_6F[48];
extern const unsigned char BIG_S_70[48];
extern const unsigned char BIG_S_71[48];
extern const unsigned char BIG_S_72[48];
extern const unsigned char BIG_S_73[48];
extern const unsigned char BIG_S_74[48];
extern const unsigned char BIG_S_75[48];
extern const unsigned char BIG_S_76[48];
extern const unsigned char BIG_S_77[48];
extern const unsigned char BIG_S_78[48];
extern const unsigned char BIG_S_79[48];
extern const unsigned char BIG_S_7A[48];
extern const unsigned char BIG_S_7B[48];
extern const unsigned char BIG_S_7C[48];
extern const unsigned char BIG_S_7D[48];
extern const unsigned char BIG_S_7E[48];
extern const unsigned char BIG_S_00[48];
extern const unsigned char *FONT_TABLE_BIG[128];

#endif // __FONT_BIG_H__
