/**
	Attention: do not modify autogenerated content

	Autogenerated by pixelfont from https://github.com/romsila/pixeltools
	Copyright (c) 2023, Roman Koch, koch.roman@gmail.com
	All rights reserved

	SPDX-License-Identifier: MIT
*/

#ifndef __FONT_HUGE_H__
#define __FONT_HUGE_H__

extern const unsigned char HUGE_S_2B[96];
extern const unsigned char HUGE_S_2D[96];
extern const unsigned char HUGE_S_2E[96];
extern const unsigned char HUGE_S_30[96];
extern const unsigned char HUGE_S_31[96];
extern const unsigned char HUGE_S_32[96];
extern const unsigned char HUGE_S_33[96];
extern const unsigned char HUGE_S_34[96];
extern const unsigned char HUGE_S_35[96];
extern const unsigned char HUGE_S_36[96];
extern const unsigned char HUGE_S_37[96];
extern const unsigned char HUGE_S_38[96];
extern const unsigned char HUGE_S_39[96];
extern const unsigned char HUGE_S_3A[96];
extern const unsigned char HUGE_S_3B[96];
extern const unsigned char HUGE_S_00[96];
extern const unsigned char *FONT_TABLE_HUGE[128];

#endif // __FONT_HUGE_H__

