/**
	Attention: do not modify autogenerated content

	Autogenerated by pixelfont from https://github.com/romsila/pixeltools
	Copyright (c) 2023, Roman Koch, koch.roman@gmail.com
	All rights reserved

	SPDX-License-Identifier: MIT
*/

#ifndef __FONT_SMALL_H__
#define __FONT_SMALL_H__

extern const unsigned char SMALL_S_20[8];
extern const unsigned char SMALL_S_21[8];
extern const unsigned char SMALL_S_22[8];
extern const unsigned char SMALL_S_23[8];
extern const unsigned char SMALL_S_24[8];
extern const unsigned char SMALL_S_25[8];
extern const unsigned char SMALL_S_26[8];
extern const unsigned char SMALL_S_27[8];
extern const unsigned char SMALL_S_28[8];
extern const unsigned char SMALL_S_29[8];
extern const unsigned char SMALL_S_2A[8];
extern const unsigned char SMALL_S_2B[8];
extern const unsigned char SMALL_S_2C[8];
extern const unsigned char SMALL_S_2D[8];
extern const unsigned char SMALL_S_2E[8];
extern const unsigned char SMALL_S_2F[8];
extern const unsigned char SMALL_S_30[8];
extern const unsigned char SMALL_S_31[8];
extern const unsigned char SMALL_S_32[8];
extern const unsigned char SMALL_S_33[8];
extern const unsigned char SMALL_S_34[8];
extern const unsigned char SMALL_S_35[8];
extern const unsigned char SMALL_S_36[8];
extern const unsigned char SMALL_S_37[8];
extern const unsigned char SMALL_S_38[8];
extern const unsigned char SMALL_S_39[8];
extern const unsigned char SMALL_S_3A[8];
extern const unsigned char SMALL_S_3B[8];
extern const unsigned char SMALL_S_3C[8];
extern const unsigned char SMALL_S_3D[8];
extern const unsigned char SMALL_S_3E[8];
extern const unsigned char SMALL_S_3F[8];
extern const unsigned char SMALL_S_40[8];
extern const unsigned char SMALL_S_41[8];
extern const unsigned char SMALL_S_42[8];
extern const unsigned char SMALL_S_43[8];
extern const unsigned char SMALL_S_44[8];
extern const unsigned char SMALL_S_45[8];
extern const unsigned char SMALL_S_46[8];
extern const unsigned char SMALL_S_47[8];
extern const unsigned char SMALL_S_48[8];
extern const unsigned char SMALL_S_49[8];
extern const unsigned char SMALL_S_4A[8];
extern const unsigned char SMALL_S_4B[8];
extern const unsigned char SMALL_S_4C[8];
extern const unsigned char SMALL_S_4D[8];
extern const unsigned char SMALL_S_4E[8];
extern const unsigned char SMALL_S_4F[8];
extern const unsigned char SMALL_S_50[8];
extern const unsigned char SMALL_S_51[8];
extern const unsigned char SMALL_S_52[8];
extern const unsigned char SMALL_S_53[8];
extern const unsigned char SMALL_S_54[8];
extern const unsigned char SMALL_S_55[8];
extern const unsigned char SMALL_S_56[8];
extern const unsigned char SMALL_S_57[8];
extern const unsigned char SMALL_S_58[8];
extern const unsigned char SMALL_S_59[8];
extern const unsigned char SMALL_S_5A[8];
extern const unsigned char SMALL_S_5B[8];
extern const unsigned char SMALL_S_5C[8];
extern const unsigned char SMALL_S_5D[8];
extern const unsigned char SMALL_S_5E[8];
extern const unsigned char SMALL_S_5F[8];
extern const unsigned char SMALL_S_60[8];
extern const unsigned char SMALL_S_61[8];
extern const unsigned char SMALL_S_62[8];
extern const unsigned char SMALL_S_63[8];
extern const unsigned char SMALL_S_64[8];
extern const unsigned char SMALL_S_65[8];
extern const unsigned char SMALL_S_66[8];
extern const unsigned char SMALL_S_67[8];
extern const unsigned char SMALL_S_68[8];
extern const unsigned char SMALL_S_69[8];
extern const unsigned char SMALL_S_6A[8];
extern const unsigned char SMALL_S_6B[8];
extern const unsigned char SMALL_S_6C[8];
extern const unsigned char SMALL_S_6D[8];
extern const unsigned char SMALL_S_6E[8];
extern const unsigned char SMALL_S_6F[8];
extern const unsigned char SMALL_S_70[8];
extern const unsigned char SMALL_S_71[8];
extern const unsigned char SMALL_S_72[8];
extern const unsigned char SMALL_S_73[8];
extern const unsigned char SMALL_S_74[8];
extern const unsigned char SMALL_S_75[8];
extern const unsigned char SMALL_S_76[8];
extern const unsigned char SMALL_S_77[8];
extern const unsigned char SMALL_S_78[8];
extern const unsigned char SMALL_S_79[8];
extern const unsigned char SMALL_S_7A[8];
extern const unsigned char SMALL_S_7B[8];
extern const unsigned char SMALL_S_7C[8];
extern const unsigned char SMALL_S_7D[8];
extern const unsigned char SMALL_S_7E[8];
extern const unsigned char SMALL_S_00[8];
extern const unsigned char *FONT_TABLE_SMALL[128];

#endif // __FONT_SMALL_H__

