/**
	Attention: do not modify autogenerated content

	Autogenerated by pixelfont from https://github.com/romsila/pixeltools
	Copyright (c) 2023, Roman Koch, koch.roman@gmail.com
	All rights reserved

	SPDX-License-Identifier: MIT
*/

#ifndef __FONT_SYMBOL_H__
#define __FONT_SYMBOL_H__

extern const unsigned char SYMBOL_S_30[32];
extern const unsigned char SYMBOL_S_31[32];
extern const unsigned char SYMBOL_S_32[32];
extern const unsigned char SYMBOL_S_33[32];
extern const unsigned char SYMBOL_S_34[32];
extern const unsigned char SYMBOL_S_35[32];
extern const unsigned char SYMBOL_S_36[32];
extern const unsigned char SYMBOL_S_37[32];
extern const unsigned char SYMBOL_S_38[32];
extern const unsigned char SYMBOL_S_39[32];
extern const unsigned char SYMBOL_S_61[32];
extern const unsigned char SYMBOL_S_64[32];
extern const unsigned char SYMBOL_S_66[32];
extern const unsigned char SYMBOL_S_67[32];
extern const unsigned char SYMBOL_S_68[32];
extern const unsigned char SYMBOL_S_73[32];
extern const unsigned char SYMBOL_S_00[32];
extern const unsigned char *FONT_TABLE_SYMBOL[128];

#endif // __FONT_SYMBOL_H__

