/**
	Attention: do not modify autogenerated content

	Autogenerated by pixelicon from https://github.com/romsila/pixeltools
	Copyright (c) 2023, Roman Koch, koch.roman@gmail.com
	All rights reserved

	SPDX-License-Identifier: MIT
*/

#ifndef __IMAGE_ADD_CIRCLE_32_H__
#define __IMAGE_ADD_CIRCLE_32_H__

extern const unsigned char IMAGE_ADD_CIRCLE_32_WIDTH;
extern const unsigned char IMAGE_ADD_CIRCLE_32_HEIGHT;

extern const unsigned char IMAGE_ADD_CIRCLE_32[128];

#endif // __IMAGE_ADD_CIRCLE_32_H__
