/**
	Attention: do not modify autogenerated content

	Autogenerated by pixelicon from https://github.com/romsila/pixeltools
	Copyright (c) 2023, Roman Koch, koch.roman@gmail.com
	All rights reserved

	SPDX-License-Identifier: MIT
*/

#include "image_add_square_8.h"

const unsigned char IMAGE_ADD_SQUARE_8_WIDTH = 8;
const unsigned char IMAGE_ADD_SQUARE_8_HEIGHT = 8;

const unsigned char IMAGE_ADD_SQUARE_8[8] = {
    0xFF, 0xFF, 0xDB, 0xFF, 0xFF, 0xDB, 0xFF, 0xFF, };
