/**
	Attention: do not modify autogenerated content

	Autogenerated by pixelicon from https://github.com/romsila/pixeltools
	Copyright (c) 2023, Roman Koch, koch.roman@gmail.com
	All rights reserved

	SPDX-License-Identifier: MIT
*/

#ifndef __IMAGE_ADD_SQUARE_8_H__
#define __IMAGE_ADD_SQUARE_8_H__

extern const unsigned char IMAGE_ADD_SQUARE_8_WIDTH;
extern const unsigned char IMAGE_ADD_SQUARE_8_HEIGHT;

extern const unsigned char IMAGE_ADD_SQUARE_8[8];

#endif // __IMAGE_ADD_SQUARE_8_H__

