/*
    Roman Koch, koch.roman@gmail.com

    Copyright (c) 2019-2021 - All rights reserved
    SPDX-License-Identifier: MIT
*/
/**
    \brief Project revision

    \internal
    \author Roman Koch, koch.roman@gmail.com
*/

#ifndef __REVISION_H__
#define __REVISION_H__

#include <cstdint>
#include <cstdlib>

#include "build_number.h"

/*

        ATTENTION: THIS FILE WAS GENERATED BY BUILD ENVIRONMENT. 
        PLEASE DO NOT CHANGE! 
        
*/


/* \name Firmware defines */
/* @{ */

namespace identity
{
    namespace firmware
    {
        /* \name Firmware identifier */
        /* @{ */
        static constexpr char PRODUCT[]= "KEYPAD_DEMO";
        static const uint16_t IDENTIFIER{1};
        static const uint16_t REVISION{(((1+0) << 8) + (1+0))};
        static const uint16_t PATCH{((0+0) << 8) + (2+0)};
        static const uint16_t BUILD{(BUILD_NUMBER)};
        static const uint16_t VENDOR{(0xBEEF)};
        static const size_t FIRMWARE_HASH_SIZE=8;
        static constexpr char FIRMWARE_HASH[]="80d84df6";
        /* @} */
    }

    namespace hardware 
    {
        /* \name Hardware identifier */
        /* @{ */
        static constexpr char PLATFORM[] = "VARIKEY";
        static const uint16_t IDENTIFIER{(1)};
        static const uint8_t  NUMBER{(1)};
        static const uint8_t  VARIANT{(0)};
        /* @} */
    }
}
/* @} */

#endif /* __REVISION_H__ */
