/**
 * \file keyboard_keycode.h
 * \author Koch, Roman (koch.roman@googlemail.com)
 * \brief
 *
 * @copyright Copyright (c) 2023, Roman Koch, koch.roman@gmail.com
 * SPDX-License-Identifier: MIT
 *
 */

#ifndef __KEYCODE_H__
#define __KEYCODE_H__

#include "tusb.h"

#define EMBEDDED_KEYBOARD

enum KEYCODE
{
#if defined(EMBEDDED_KEYBOARD)
    KEYBOARD_1_LEFT = HID_KEY_ESCAPE,
    KEYBOARD_2_LEFT = HID_KEY_F2,
    KEYBOARD_3_LEFT = HID_KEY_F1,
    KEYBOARD_4_LEFT = HID_KEY_F3,
    KEYBOARD_5_LEFT = HID_KEY_F4,
    KEYBOARD_1_RIGHT = HID_KEY_F5,
    KEYBOARD_2_RIGHT = HID_KEY_F6,
    KEYBOARD_3_RIGHT = HID_KEY_F7,
    KEYBOARD_4_RIGHT = HID_KEY_F8,
    KEYBOARD_5_RIGHT = HID_KEY_F9,
    KEYBOARD_LEFT = HID_KEY_PAGE_DOWN,
    KEYBOARD_RIGHT = HID_KEY_PAGE_UP,
    KEYBOARD_PUSH = HID_KEY_ENTER,
#else
    KEYBOARD_1_LEFT = HID_KEY_0,
    KEYBOARD_2_LEFT = HID_KEY_1,
    KEYBOARD_3_LEFT = HID_KEY_2,
    KEYBOARD_4_LEFT = HID_KEY_3,
    KEYBOARD_5_LEFT = HID_KEY_4,
    KEYBOARD_1_RIGHT = HID_KEY_5,
    KEYBOARD_2_RIGHT = HID_KEY_6,
    KEYBOARD_3_RIGHT = HID_KEY_7,
    KEYBOARD_4_RIGHT = HID_KEY_8,
    KEYBOARD_5_RIGHT = HID_KEY_9,
    KEYBOARD_LEFT = HID_KEY_PAGE_DOWN,
    KEYBOARD_RIGHT = HID_KEY_PAGE_UP,
    KEYBOARD_PUSH = HID_KEY_ENTER,
#endif
};

#endif // __KEYCODE_H__
