/**
	Attention: do not modify autogenerated content

	Autogenerated by pixelicon from https://github.com/romsila/pixeltools
	Copyright (c) 2023, Roman Koch, koch.roman@gmail.com
	All rights reserved

	SPDX-License-Identifier: MIT
*/

#include "image_add_circle_8.h"

const unsigned char IMAGE_ADD_CIRCLE_8_WIDTH = 8;
const unsigned char IMAGE_ADD_CIRCLE_8_HEIGHT = 8;

const unsigned char IMAGE_ADD_CIRCLE_8[8] = {
	0x7E,
	0xFF,
	0xDB,
	0xFF,
	0xFF,
	0xDB,
	0xFF,
	0x7E,
};
