/**
	Attention: do not modify autogenerated content

	Autogenerated by pixelicon from https://github.com/romsila/pixeltools
	Copyright (c) 2023, Roman Koch, koch.roman@gmail.com
	All rights reserved

	SPDX-License-Identifier: MIT
*/

#include "image_add_square_16.h"

const unsigned char IMAGE_ADD_SQUARE_16_WIDTH = 16;
const unsigned char IMAGE_ADD_SQUARE_16_HEIGHT = 16;

const unsigned char IMAGE_ADD_SQUARE_16[32] = {
	0xF8,
	0x1F,
	0xFE,
	0x7F,
	0xFF,
	0xFF,
	0x07,
	0xE0,
	0x87,
	0xE1,
	0xC7,
	0xE3,
	0xE7,
	0xE7,
	0xF7,
	0xEF,
	0xF7,
	0xEF,
	0xE7,
	0xE7,
	0xC7,
	0xE3,
	0x87,
	0xE1,
	0x07,
	0xE0,
	0xFF,
	0xFF,
	0xFE,
	0x7F,
	0xF8,
	0x1F,
};
