# Copyright (c) 2023, Roman Koch, koch.roman@gmail.com
# SPDX-License-Identifier: MIT

#basic definitions
set(HEADER_FILE "build_number.h")
set(CACHE_FILE "build_number.cache")

#Reading data from file + incrementation
IF(EXISTS ${CACHE_FILE})
    file(READ ${CACHE_FILE} INCREMENTED_VALUE)
    math(EXPR INCREMENTED_VALUE "${INCREMENTED_VALUE}+1")
	if(INCREMENTED_VALUE GREATER "65535")
		set(INCREMENTED_VALUE "0")
	endif(INCREMENTED_VALUE GREATER "65535")
ELSE()
    set(INCREMENTED_VALUE "0")
ENDIF()

#Update the cache
file(WRITE ${CACHE_FILE} "${INCREMENTED_VALUE}")

#Create the header
message("Generate build number ${INCREMENTED_VALUE} for the next build to ${CMAKE_CURRENT_SOURCE_DIR}/../src/${HEADER_FILE}")
file(WRITE "${CMAKE_CURRENT_SOURCE_DIR}/../varikey_library/${HEADER_FILE}" 
"/*	
	Copyright (c) 2023, Roman Koch, koch.roman@gmail.com
	SPDX-License-Identifier: MIT
*/

#pragma once 

// Attention: autogenerated file
#define BUILD_NUMBER ${INCREMENTED_VALUE}

")
